---
- name: Install pre reqs
  apt: >
    name=python3-apt
    state=installed

- name: Download vagrant package
  get_url: >
    url={{ vagrant_url }}
    dest={{ vagrant_destination }}

- name: Install vagrant
  apt: >
    deb={{ vagrant_destination }}/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
    state=installed
